arquivo = open("arquivo.txt", "w", encoding="utf-8")


nome = input("digite seu nome: \n")
arquivo.write(f"\naluno: {nome}\n")
nome = input("digite seu nome: \n")
arquivo.write(f"\naluno: {nome}\n")
nome = input("digite seu nome: \n")
arquivo.write(f"\naluno: {nome}\n")
nome = input("digite seu nome: \n")
arquivo.write(f"\naluno: {nome}\n")
nome = input("digite seu nome: \n")
arquivo.write(f"\naluno: {nome}\n")
nome = input("digite seu nome: \n")
arquivo.write(f"\naluno: {nome}\n")
nome = input("digite seu nome: \n")
arquivo.write(f"\naluno: {nome}\n")
nome = input("digite seu nome: \n")
arquivo.write(f"\naluno: {nome}\n")
nome = input("digite seu nome: \n")
arquivo.write(f"\naluno: {nome}\n")
nome = input("digite seu nome: \n")
arquivo.write(f"\naluno: {nome}\n")
nome = input("digite seu nome: \n")
arquivo.write(f"\naluno: {nome}\n")
nome = input("digite seu nome: \n")
arquivo.write(f"\naluno: {nome}\n")
nome = input("digite seu nome: \n")
arquivo.write(f"\naluno: {nome}\n")
nome = input("digite seu nome: \n")
arquivo.write(f"\naluno: {nome}\n")
nome = input("digite seu nome: \n")
arquivo.write(f"\naluno: {nome}\n")
nome = input("digite seu nome: \n")
arquivo.write(f"\naluno: {nome}\n")
nome = input("digite seu nome: \n")
arquivo.write(f"\naluno: {nome}\n")
nome = input("digite seu nome: \n")
arquivo.write(f"\naluno: {nome}\n")
nome = input("digite seu nome: \n")
arquivo.write(f"\naluno: {nome}\n")

arquivo.close()