a = []

x = input("digite seu nome: \n")
a.append("digite seu nome: \n")
a.append(x)
a.append("digite seu nome: \n")
a.append(x)
a.append("digite seu nome: \n")
a.append(x)
a.append("digite seu nome: \n")
a.append(x)
a.append("digite seu nome: \n")
a.append(x)
a.append("digite seu nome: \n")
a.append(x)
a.append("digite seu nome: \n")
a.append(x)
a.append("digite seu nome: \n")
a.append(x)
a.append("digite seu nome: \n")
a.append(x)
a.append("digite seu nome: \n")
a.append(x)
a.append("digite seu nome: \n")
a.append(x)

print(x)