a = []

x = input("digite seu carro: \n")
a.append("digite seu carro: \n")
a.append(x)
a.append("digite seu carro: \n")
a.append(x)
a.append("digite seu carro: \n")
a.append(x)
a.append("digite seu carro: \n")
a.append(x)
a.append("digite seu carro: \n")
a.append(x)
a.append("digite seu carro: \n")
a.append(x)
a.append("digite seu carro: \n")
a.append(x)
a.append("digite seu carro: \n")
a.append(x)
a.append("digite seu carro: \n")
a.append(x)
a.append("digite seu carro: \n")
a.append(x)

print(x)